[tool.commitizen]
name = "cz_conventional_commits"
version = "1.7.0"
version_files = [
    "club-pongiste-libercourtois/package.json:\"version\""
]
tag_format = "v$version"
update_changelog_on_bump = true
