repos:
  # Prettier for code formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        exclude: |
          (?x)^(
            node_modules/.*|
            \.nuxt/.*|
            dist/.*|
            \.output/.*|
            package-lock\.json
          )$

  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-json
        exclude: package-lock\.json
      - id: trailing-whitespace
        exclude: \.md$
      - id: end-of-file-fixer
      - id: check-added-large-files
        args: ["--maxkb=2048"]
        exclude: |
          (?x)^(
            .*package-lock\.json|
            .*\.(jpg|jpeg|png|gif|webp|svg)$
          )$

  # Markdownlint
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.39.0
    hooks:
      - id: markdownlint
        args: ["--fix"]

  # Commitizen for conventional commits
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.29.1
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages: [manual]

  # ESLint for JavaScript/TypeScript/Vue
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: bash -c 'cd club-pongiste-libercourtois && pnpm lint:check'
        language: system
        types: [javascript, ts, vue]
        pass_filenames: false

  # TypeScript type checking
  - repo: local
    hooks:
      - id: typecheck
        name: typecheck
        entry: bash -c 'cd club-pongiste-libercourtois && pnpm typecheck'
        language: system
        types: [ts, vue]
        pass_filenames: false

  # Playwright tests (only on main files changes)
  - repo: local
    hooks:
      - id: playwright-tests
        name: playwright-tests
        entry: bash -c 'cd club-pongiste-libercourtois && pnpm test:e2e'
        language: system
        files: '^club-pongiste-libercourtois/(pages/|components/|layouts/|app\.vue)'
        pass_filenames: false

exclude: |
  (?x)^(
    \.venv/.*|
    node_modules/.*|
    \.nuxt/.*|
    dist/.*|
    \.output/.*
  )$
